from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
PAGE=ROOT/"app"/"page.tsx"
MARKER="// GROUPED_CATALOG_V93"

def need(text,fragment,label):
    if fragment not in text: raise SystemExit(f"{label}: fragment not found")
    return text

def main():
    text=PAGE.read_text(encoding="utf-8")
    if MARKER in text:
        print(f"{MARKER}: already applied")
        return

    start=text.find("// GROUPED_CATALOG_V92"); end=text.find("// CATALOG_PRODUCT_NORMALIZATION_V74",start)
    if start<0 or end<0: raise SystemExit("helpers region not found")
    helpers='''// GROUPED_CATALOG_V93\nconst cleanNulls=(value:unknown)=>{const text=String(value??"").trim();return !text||text==="null"?undefined:text};\nconst splitMultiline=(value:unknown)=>{const text=cleanNulls(value);return text?text.split(/\\\\n|\\n|\\u2028|\\u2029/g).map(part=>part.trim()).filter(Boolean):[]};\nconst renderMultiline=(value:unknown)=>{const parts=splitMultiline(value);return parts.length?<>{parts.map((part,index)=><span key={`${part}-${index}`} style={{display:"block",lineHeight:1.18,margin:0}}>{part}</span>)}</>:null};\nconst parseCatalogPrice=(value:unknown)=>Number(String(cleanNulls(value)??"").replace(/[^\\d.,-]/g,"").replace(",","."))||0;\n'''
    text=text[:start]+helpers+text[end:]

    need(text,'const scentMode=category==="Декор для дома"&&subcategory==="Свечи и диффузоры"&&scents.length>1;','scent mode')
    text=text.replace('const scentMode=category==="Декор для дома"&&subcategory==="Свечи и диффузоры"&&scents.length>1;','const scentMode=scents.length>0&&variants.length>1;',1)

    fs=text.find("function findProductSku("); fe=text.find("function ScrollableProductMedia",fs)
    if fs<0 or fe<0: raise SystemExit("variant helpers region not found")
    variant_helpers='''type VariantSku=CatalogSku&{scent?:string;sourceColor?:string;volume?:string;oldPrice?:number};\nconst asVariantSku=(sku:CatalogSku|undefined)=>sku as VariantSku|undefined;\nfunction skuPrimaryMatches(product:Product,sku:CatalogSku,primary?:string){if(!primary)return true;const extra=asVariantSku(sku);return isAromaProduct(product)?extra?.scent===primary:(extra?.sourceColor??sku.color)===primary}\nfunction findProductSku(product:Product,primary?:string,size?:string,secondaryColor?:string){\n  if(!product.skus?.length)return undefined;\n  const match=(item:CatalogSku)=>skuPrimaryMatches(product,item,primary)&&(!secondaryColor||asVariantSku(item)?.sourceColor===secondaryColor)&&(!size||item.size===size);\n  const selected=product.selectedSkuId?product.skus.find(item=>item.id===product.selectedSkuId):undefined;\n  if(selected&&match(selected))return selected;\n  return product.skus.find(match)??product.skus.find(item=>skuPrimaryMatches(product,item,primary))??product.skus[0];\n}\nfunction getProductSecondaryColors(product:Product,primary?:string){\n  if(!isAromaProduct(product)||!product.skus?.length)return [] as {name:string;hex:string}[];\n  const map=new Map<string,{name:string;hex:string}>();\n  product.skus.filter(item=>skuPrimaryMatches(product,item,primary)).forEach(item=>{const name=cleanNulls(asVariantSku(item)?.sourceColor);if(name&&!map.has(name))map.set(name,{name,hex:item.colorHex})});\n  return Array.from(map.values());\n}\nfunction getProductSizeOptions(product:Product,primary?:string,secondaryColor?:string){\n  if(product.skus?.length){const rows=product.skus.filter(item=>skuPrimaryMatches(product,item,primary)&&(!secondaryColor||asVariantSku(item)?.sourceColor===secondaryColor));return Array.from(new Map(rows.map(item=>[item.size,[item.size,item.price] as const])).values())}\n  return [["Евро 200×220",product.price],["Семейный 150×200",product.price+2000],["Кинг Сайз 220×240",product.price+2000]] as const;\n}\nfunction isProductSizeAvailable(product:Product,primary:string|undefined,size:string,secondaryColor?:string){const rows=product.skus?.filter(item=>skuPrimaryMatches(product,item,primary)&&(!secondaryColor||asVariantSku(item)?.sourceColor===secondaryColor)&&item.size===size);if(!rows?.length)return true;return rows.some(item=>item.available!==false)}\nfunction getUnavailableProductSizes(product:Product,primary:string|undefined,sizes:readonly (readonly [string,number])[],secondaryColor?:string){return sizes.filter(([name])=>!isProductSizeAvailable(product,primary,name,secondaryColor)).map(([name])=>name)}\n\n'''
    text=text[:fs]+variant_helpers+text[fe:]

    cs=text.find("function CatalogView("); ce=text.find("function ProductCard(",cs)
    if cs<0 or ce<0: raise SystemExit("CatalogView region not found")
    catalog='''function CatalogView({ initialCategory, onFilter:_onFilter, onAdd, onProduct, favorite, favorites }: { initialCategory:string; onFilter:()=>void; onAdd:(p:Product)=>void; onProduct:(p:Product)=>void; favorite:(n:number)=>void; favorites:number[] }) {\n  const [sort,setSort]=useState("По умолчанию");\n  const categoryNames=Array.from(new Set(products.map(product=>cleanNulls(product.category)).filter((value):value is string=>Boolean(value))));\n  const resolveCategory=(value:string)=>categoryNames.find(name=>name.toLocaleLowerCase("ru-RU").replace(/ё/g,"е")===String(value||"").toLocaleLowerCase("ru-RU").replace(/ё/g,"е"))??"Все товары";\n  const [category,setCategory]=useState(()=>resolveCategory(initialCategory));\n  const [subcategory,setSubcategory]=useState("Все подкатегории");\n  useEffect(()=>{setCategory(resolveCategory(initialCategory));setSubcategory("Все подкатегории")},[initialCategory,categoryNames.join("|")]);\n  const subcategories=category==="Все товары"?[]:Array.from(new Set(products.filter(product=>product.category===category).map(product=>cleanNulls(product.subcategory)).filter((value):value is string=>Boolean(value))));\n  const list=products.filter(product=>(category==="Все товары"||product.category===category)&&(subcategory==="Все подкатегории"||product.subcategory===subcategory)).sort((a,b)=>sort==="Сначала дешевле"?a.price-b.price:sort==="Сначала дороже"?b.price-a.price:a.id-b.id);\n  return <div className="catalog page"><div className="crumbs">Главная / Каталог / {category}</div><div className="title-line"><h1>{category}</h1><span>{productCountLabel(list.length)}</span></div>\n    <div className="tabs">{["Все товары",...categoryNames].map(name=><button key={name} className={category===name?"active":""} onClick={()=>{setCategory(name);setSubcategory("Все подкатегории")}}>{name}</button>)}</div>\n    <div className="catalog-tools"><select value={sort} onChange={event=>setSort(event.target.value)}><option>По умолчанию</option><option>Сначала дешевле</option><option>Сначала дороже</option></select>{category!=="Все товары"&&subcategories.length>0&&<label style={{display:"flex",alignItems:"center",gap:8}}><Icon name="filter"/><select aria-label="Подкатегория" value={subcategory} onChange={event=>setSubcategory(event.target.value)}><option>Все подкатегории</option>{subcategories.map(name=><option key={name}>{name}</option>)}</select></label>}</div>\n    {list.length?<div className="product-grid">{list.map(product=><ProductCard key={`${category}-${subcategory}-${product.id}`} product={product} onClick={onProduct} onQuick={onAdd} favorite={favorite} liked={favorites.includes(product.id)}/>)}</div>:<div className="catalog-empty"><p>В этой категории пока нет товаров</p></div>}\n  </div>;\n}\n\n'''
    text=text[:cs]+catalog+text[ce:]

    old='  const [selectedSize,setSelectedSize]=useState("");\n  const [quantity,setQuantity]=useState(1);'
    need(text,old,'PDP state'); text=text.replace(old,'  const [selectedSize,setSelectedSize]=useState("");\n  const [selectedSecondaryColor,setSelectedSecondaryColor]=useState("");\n  const [quantity,setQuantity]=useState(1);',1)

    old='''  useEffect(()=>{const initial=variants.findIndex(variant=>variant.name===product.selectedColor);const nextIndex=initial>=0?initial:0;setColorIndex(nextIndex);setActiveImage(0);setSelectedSize("");setQuantity(1);setSizePrompt(false)},[product.id,product.selectedColor]);\n  const color=variants[colorIndex];\n  const sizes=getProductSizeOptions(product,color.name);\n  const unavailableSizes=getUnavailableProductSizes(product,color.name,sizes);\n  const autoSize=sizes.length===1&&isProductSizeAvailable(product,color.name,sizes[0][0])?sizes[0][0]:"";\n  const effectiveSelectedSize=selectedSize||autoSize;\n  const sku=effectiveSelectedSize?findProductSku(product,color.name,effectiveSelectedSize):undefined;\n  const mediaSku=findProductSku(product,color.name);\n  const gallery=mediaSku?[mediaSku.image,...mediaSku.gallery]:product.hasRichContent?[color.image]:(product.gallery??[color.image,...variants.map(x=>x.image)]).filter((x,i,a)=>a.indexOf(x)===i);\n  const unitPrice=sku?.price??(sizes.length?Math.min(...sizes.map(([,value])=>value)):product.price);\n  const selectedProduct={...product,price:unitPrice,image:mediaSku?.image??color.image,gallery:mediaSku?.gallery??product.gallery,selectedColor:color.name,selectedSize:effectiveSelectedSize,selectedSkuId:sku?.id,quantity};\n  const specs=sku??mediaSku??product.skus?.[0];\n  const specsExtra=specs as (CatalogSku&{volume?:string;oldPrice?:number})|undefined;'''
    new='''  useEffect(()=>{const initial=variants.findIndex(variant=>variant.name===product.selectedColor);const nextIndex=initial>=0?initial:0;setColorIndex(nextIndex);setActiveImage(0);setSelectedSize("");setSelectedSecondaryColor("");setQuantity(1);setSizePrompt(false)},[product.id,product.selectedColor]);\n  const color=variants[colorIndex];\n  const secondaryColors=getProductSecondaryColors(product,color.name);\n  const secondaryColor=secondaryColors.some(item=>item.name===selectedSecondaryColor)?selectedSecondaryColor:(secondaryColors[0]?.name??"");\n  const sizes=getProductSizeOptions(product,color.name,secondaryColor||undefined);\n  const unavailableSizes=getUnavailableProductSizes(product,color.name,sizes,secondaryColor||undefined);\n  const autoSize=sizes.length===1&&isProductSizeAvailable(product,color.name,sizes[0][0],secondaryColor||undefined)?sizes[0][0]:"";\n  const effectiveSelectedSize=selectedSize||autoSize;\n  const sku=effectiveSelectedSize?findProductSku(product,color.name,effectiveSelectedSize,secondaryColor||undefined):undefined;\n  const mediaSku=findProductSku(product,color.name,undefined,secondaryColor||undefined);\n  const gallery=mediaSku?[mediaSku.image,...mediaSku.gallery]:product.hasRichContent?[color.image]:(product.gallery??[color.image,...variants.map(x=>x.image)]).filter((x,i,a)=>a.indexOf(x)===i);\n  const unitPrice=sku?.price??(sizes.length?Math.min(...sizes.map(([,value])=>value)):product.price);\n  const sizePricesDiffer=new Set(sizes.map(([,value])=>value)).size>1;\n  const showFromPrice=sizes.length>1&&sizePricesDiffer&&!selectedSize;\n  const selectedProduct={...product,price:unitPrice,image:mediaSku?.image??color.image,gallery:mediaSku?.gallery??product.gallery,selectedColor:color.name,selectedSize:effectiveSelectedSize,selectedSkuId:(sku??mediaSku)?.id,quantity};\n  const specs=sku??mediaSku??product.skus?.[0];\n  const specsExtra=asVariantSku(specs);'''
    need(text,old,'PDP variant calc'); text=text.replace(old,new,1)

    text=text.replace('const needsSize=Boolean(sizes.length&&!effectiveSelectedSize);','const needsSize=Boolean(sizes.length>1&&!effectiveSelectedSize);',1)
    text=text.replace('isProductSizeAvailable(product,color.name,effectiveSelectedSize)','isProductSizeAvailable(product,color.name,effectiveSelectedSize,secondaryColor||undefined)',1)
    text=text.replace('sizes.length>1&&!selectedSize?`от ${fmt(unitPrice)}`:fmt(unitPrice)','showFromPrice?`от ${fmt(unitPrice)}`:fmt(unitPrice)',1)

    old='{product.switchBy!=="none"&&<label className="pdp-color-label">{isAromaProduct(product)?"Аромат":"Цвет"}: {color.name}</label>}{isAromaProduct(product)&&variants.length>1&&<div className="pdp-aroma-options">{variants.map((variant,index)=><button key={variant.name} className={index===colorIndex?"active":""} onClick={()=>{setColorIndex(index);setActiveImage(0);setSelectedSize("");setQuantity(1);setSizePrompt(false)}}>{variant.name}</button>)}</div>}{product.switchBy==="color"&&variants.length>1&&<div className="swatches product-swatches">{variants.map((variant,index)=><button key={variant.name} className={index===colorIndex?"active":""} onClick={()=>{setColorIndex(index);setActiveImage(0);setSelectedSize("");setQuantity(1);setSizePrompt(false)}} style={{background:variant.hex}} aria-label={`Цвет ${variant.name}`}/>)}</div>}'
    new='{product.switchBy!=="none"&&<label className="pdp-color-label">{isAromaProduct(product)?"Аромат":"Цвет"}: {color.name}</label>}{isAromaProduct(product)&&variants.length>1&&<div className="pdp-aroma-options">{variants.map((variant,index)=><button key={variant.name} className={index===colorIndex?"active":""} onClick={()=>{setColorIndex(index);setSelectedSecondaryColor("");setActiveImage(0);setSelectedSize("");setQuantity(1);setSizePrompt(false)}}>{variant.name}</button>)}</div>}{isAromaProduct(product)&&secondaryColors.length>0&&<><label className="pdp-color-label">Цвет: {secondaryColor}</label>{secondaryColors.length>1&&<div className="swatches product-swatches">{secondaryColors.map(item=><button key={item.name} className={item.name===secondaryColor?"active":""} onClick={()=>{setSelectedSecondaryColor(item.name);setActiveImage(0);setSelectedSize("");setQuantity(1);setSizePrompt(false)}} style={{background:item.hex}} aria-label={`Цвет ${item.name}`}/>)}</div>}</>}{product.switchBy==="color"&&variants.length>1&&<div className="swatches product-swatches">{variants.map((variant,index)=><button key={variant.name} className={index===colorIndex?"active":""} onClick={()=>{setColorIndex(index);setActiveImage(0);setSelectedSize("");setQuantity(1);setSizePrompt(false)}} style={{background:variant.hex}} aria-label={`Цвет ${variant.name}`}/>)}</div>}'
    need(text,old,'PDP selectors'); text=text.replace(old,new,1)

    old='<label className="pdp-size-head"><span>РАЗМЕР</span><button onClick={()=>alert(sizes.map(([name])=>name).join(" · "))}>Руководство по размерам</button></label><ProductSizeRows sizes={sizes} selectedSize={effectiveSelectedSize} setSelectedSize={(name)=>{setSelectedSize(name);setQuantity(1);setSizePrompt(false)}} quantity={quantity} setQuantity={setQuantity} unavailableLast={!product.skus?.length} unavailableSizes={unavailableSizes} oldPrice={product.oldPrice} notify={(name)=>alert(`Спасибо. Сообщим, когда размер «${name}» появится в наличии.`)}/>'
    new='{sizes.length>1&&<><label className="pdp-size-head"><span>РАЗМЕР</span><button onClick={()=>alert(sizes.map(([name])=>name).join(" · "))}>Руководство по размерам</button></label><ProductSizeRows sizes={sizes} selectedSize={effectiveSelectedSize} setSelectedSize={(name)=>{setSelectedSize(name);setQuantity(1);setSizePrompt(false)}} quantity={quantity} setQuantity={setQuantity} unavailableLast={!product.skus?.length} unavailableSizes={unavailableSizes} oldPrice={product.oldPrice} notify={(name)=>alert(`Спасибо. Сообщим, когда размер «${name}» появится в наличии.`)}/></>}'
    need(text,old,'PDP size'); text=text.replace(old,new,1)

    text=text.replace('<div className="crumbs">Главная / Домашний текстиль / {product.name}</div>','<div className="crumbs">Главная / {product.category??"Каталог"} / {product.name}</div>',1)
    PAGE.write_text(text,encoding="utf-8")
    print(f"{MARKER}: aroma > color > size, exact CSV categories, subcategory filter, multiline/null rendering")

if __name__=="__main__": main()
